import React,{useMemo,useState}from"react";import*as XLSX from"xlsx";import"./DataQualityStudio.css";
const demo=[["Customer","Email","Amount","Date","Status"],["Aman","aman@email.com","1200","2026-01-05","Paid"],["Aman","aman@email.com","1200","2026-01-05","Paid"],["Neha"," ","950","bad-date","Paid"],["Ravi","ravi@email.com","","2026-02-10","Pending"],["Sara","sara@email.com","-20","2026-03-01","paid"]];
export default function DataQualityStudio(){
const[data,setData]=useState(demo),[q,setQ]=useState(""),[msg,setMsg]=useState("Ready");
const h=data[0]||[],rows=data.slice(1);
const result=useMemo(()=>{let blank=0,dup=0,badDate=0,negative=0;const seen=new Set();rows.forEach(r=>{if(r.some(v=>String(v??"").trim()===""))blank++;let k=JSON.stringify(r);if(seen.has(k))dup++;seen.add(k);let d=r[h.indexOf("Date")];if(d&&isNaN(Date.parse(d)))badDate++;let a=Number(r[h.indexOf("Amount")]);if(Number.isFinite(a)&&a<0)negative++});const issues=blank+dup+badDate+negative;return{blank,dup,badDate,negative,issues,score:Math.max(0,Math.round(100-(issues/Math.max(rows.length,1))*15))}},[data]);
async function load(e){const f=e.target.files?.[0];if(!f)return;try{const b=await f.arrayBuffer(),w=XLSX.read(b,{type:"array"}),s=w.SheetNames[0],r=XLSX.utils.sheet_to_json(w.Sheets[s],{header:1,defval:""});setData(r);setMsg("Imported: "+f.name)}catch{x=>setMsg("Import failed")}e.target.value=""}
function clean(){const seen=new Set(),out=[h];rows.forEach(r=>{const x=r.map(v=>typeof v==="string"?v.trim():v);const k=JSON.stringify(x);if(!seen.has(k)){seen.add(k);out.push(x)}});setData(out);setMsg("Trimmed text + duplicates removed")}
function exportFile(){const w=XLSX.utils.book_new();XLSX.utils.book_append_sheet(w,XLSX.utils.aoa_to_sheet(data),"Cleaned Data");XLSX.writeFile(w,"cleaned-data.xlsx");setMsg("Cleaned XLSX exported")}
const filtered=rows.filter(r=>!q||r.some(v=>String(v??"").toLowerCase().includes(q.toLowerCase())));
return <div className="dqs"><header><div><span>DATA QUALITY</span><h1>Data Quality Studio</h1><p>Inspect, validate, clean and prepare business datasets.</p></div><label className="dqs-btn primary">Import CSV/XLSX<input hidden type="file" accept=".csv,.xlsx,.xls" onChange={load}/></label></header><div className="dqs-kpis"><article><small>Quality Score</small><b>{result.score}%</b></article><article><small>Rows</small><b>{rows.length}</b></article><article><small>Missing Rows</small><b>{result.blank}</b></article><article><small>Duplicates</small><b>{result.dup}</b></article><article><small>Invalid Dates</small><b>{result.badDate}</b></article><article><small>Negative Values</small><b>{result.negative}</b></article></div><div className="dqs-tools"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search dataset..."/><button onClick={clean}>🧹 Clean Data</button><button onClick={exportFile}>Export Clean XLSX</button><em>{msg}</em></div><div className="dqs-grid"><section className="dqs-card"><h3>Data Quality Checks</h3><div className="check"><span>Missing values</span><b>{result.blank?"Review":"PASS"}</b></div><div className="check"><span>Duplicate records</span><b>{result.dup?"Review":"PASS"}</b></div><div className="check"><span>Invalid dates</span><b>{result.badDate?"Review":"PASS"}</b></div><div className="check"><span>Negative amounts</span><b>{result.negative?"Review":"PASS"}</b></div></section><section className="dqs-card table"><h3>Dataset Preview</h3><div><table><thead><tr>{h.map((x,i)=><th key={i}>{String(x||`Column ${i+1}`)}</th>)}</tr></thead><tbody>{filtered.slice(0,100).map((r,i)=><tr key={i}>{h.map((_,c)=><td key={c}>{String(r[c]??"")}</td>)}</tr>)}</tbody></table></div></section></div></div>}

